### ISSUE TITLE
Bug: Popup windows randomly disappear

### ISSUE THREAD

**Issue by shawly** [mindflayer-vtt/foundryvtt-mindflayer-brainmate#2]
When using an item like a weapon to make an attack and press the "Attack" or "Damage" buttons they grey out but the popup for rolling dice does not appear.

**Comment by shawly** [comment]
Same goes for spell popups if they require selecting spell slots or placing measurement templates

**Comment by shawly** [comment]
Settings also don't open up so I guess the issue is that some popup windows aren't placed on top of the ui

**Comment by shawly** [comment]
Logging out and back in fixes the issue

**Comment by 749** [comment]
I am currently unable to recreate the issue, please let me know the exact steps to recreate and if it still is an issue.

**Comment by shawly** [comment]
~I couldn't reproduce this either but it happened twice, so we should keep this open in case it happens again.~

Changed my mind, I think we can close this until it happens again.
