### ISSUE TITLE
Macro bar - Context menu is hidden behind main window

### ISSUE THREAD

**Issue by shawly** [mindflayer-vtt/foundryvtt-mindflayer-brainmate#3]
When I tap on the macro bar the popup to create a new macro appears and I can add macros, the problem is if I long press the macro the context menu is hidden behind the main window so I can't access it to delete the macro again.

**Comment by 749** [comment]
With dev-tools on Chromium it shows the menu, on android device only the tooltip opens not the menu.

**Comment by 749** [comment]
confirmed working in v1.0.6 commit: [a119c0b](https://github.com/mindflayer-vtt/foundryvtt-mindflayer-brainmate/commit/a119c0bdf399e1c9120cebc8c8c1162c796d9bea)
