### ISSUE TITLE
Make character sheet accessible faster

### ISSUE THREAD

**Issue by shawly** [mindflayer-vtt/foundryvtt-mindflayer-brainmate#4]
Navigating between character sheet and chat to make attack and damage rolls requires a lot of navigating through the UI.

Since a character is usually linked to a player directly we might add a floating bubble with the character portrait or something similar to the UI so we can access our main character sheet from every tab which makes it more user friendly.

**Comment by shawly** [comment]
Method `ClientKeybindings._onToggleCharacterSheet(event, context)`  can be bound to the bubble or button which works even without arguments

**Comment by 749** [comment]
confirmed working after cache-clear
