### ISSUE TITLE
Bug:  Spell usage & Spell target texts are overlapping in mobile view

### ISSUE THREAD

**Issue by Smokey62** [mindflayer-vtt/foundryvtt-mindflayer-brainmate#5]
When looking at the spells tab in mobile view (Tablet, resolution 800x1200px), the texts for spell usage and spell target are overlapping.

![Screenshot_20220301-171928_Firefox](https://user-images.githubusercontent.com/20574843/156416312-d463cd44-b0c5-4d15-b2b6-7536b1507ed8.jpg)

**Comment by shawly** [comment]
Setting `.dnd5e.sheet .items-list .items-header` height to auto fixes the overflow issue

Also overriding https://github.com/mindflayer-vtt/foundryvtt-mindflayer-brainmate/blob/82a3ae904457dd6213f090f89e688cde3b5d2193/src/sass/index.sass#L210 with `flex: 0 0 100px` as well as https://github.com/mindflayer-vtt/foundryvtt-mindflayer-brainmate/blob/82a3ae904457dd6213f090f89e688cde3b5d2193/src/sass/index.sass#L203 with `flex: 0 0 50px` makes the ui a bit fat finger friendlier.

**Comment by shawly** [comment]
`.imp-cls__btn-sheet-level-up` should also be set to `display: none` since the level up wizard is not visible anyway when clicking the button and we usually don't level up mid session.

![image](https://user-images.githubusercontent.com/6448794/156442493-1bccfa58-8ce6-47ed-b4a0-8dd57bc771cb.png)

**Comment by 749** [comment]
should now be fixed, please validate @Smokey62

**Comment by shawly** [comment]
All issues fixed
