### ISSUE TITLE
Feature Request: Close focused windows with back button when in mobile view

### ISSUE THREAD

**Issue by Smokey62** [mindflayer-vtt/foundryvtt-mindflayer-brainmate#6]
It would be nice to be able to close focused windows, for example the details window of items, by using the back button of mobile devices. Right now pressing the back button leads back to the login screen of VTT.

**Comment by shawly** [comment]
Just tested, this works for the most part:

```javascript
history.pushState(null, null, window.top.location.pathname + window.top.location.search);
        window.addEventListener('popstate', (e) => {
            e.preventDefault();
            ui.activeWindow.close();
            history.pushState(null, null, window.top.location.pathname + window.top.location.search);
        });
```

Problem is, if you open the character window, then open another popup and close that popup with this, then the character sheet is not in focus anymore, so we need to add logic to make the previous window the "activeWindow" again.

Also the first time you press the back button an alert window pops up and asks if you want to close foundry (at least on the desktop).

**Comment by shawly** [comment]
With `ui.windows` we can get a map of open windows, so we can set the last open window to be the active window.

**Comment by shawly** [comment]
```javascript
history.pushState(null, null, location.href);
game._goingBack = true;
window.addEventListener('popstate', (e) => {
    e.preventDefault();
    ClientKeybindings._onDismiss();
    history.pushState(null, null, location.href);
});
```

Crappy code confirmed working on Android, and alert message is fixed as well.

Clean implementation should simply override `_onWindowPopState(event)` with LibWrapper so we don't have to set `game._goingBack` anymore.

**Edit:** Improved with `ClientKeybindings._onDismiss()`
